insert into properties (property_name, price, currency, property_image,property_image2,property_image3,property_location,beds,baths,description,property_id,property_type,area,garage) values ('California, USA', 1291000, '$', '/images/img_1.jpg','/images/img_2.jpg','/images/img_4.jpg','5232 California Fake, Ave. 21BC','3 beds','1 baths','Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec velit neque, auctor sit amet aliquam vel, ullamcorper sit amet ligula. Cras ultricies ligula sed magna dictum porta. Curabitur aliquet quam id dui posuere blandit. Mauris blandit aliquet elit, eget tincidunt nibh pulvinar quam id dui posuere blandit.
Curabitur arcu erat, accumsan id imperdiet et, porttitor at sem. Donec rutrum congue leo eget malesuada. Quisque velit nisi, pretium ut lacinia in, elementum id enim. Donec sollicitudin molestie malesuada.','77','Villa','340m','1');
insert into properties (property_name, price, currency, property_image,property_image2,property_image3,property_location,beds,baths,description,property_id,property_type,area,garage) values ('New Mexico, USA', 3600000, '$', '/images/img_2.jpg','/images/img_5.jpg','/images/img_1.jpg','9524 Mexico Highway, Ave. 36XR','3 beds','1 baths','Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec velit neque, auctor sit amet aliquam vel, ullamcorper sit amet ligula. Cras ultricies ligula sed magna dictum porta. Curabitur aliquet quam id dui posuere blandit. Mauris blandit aliquet elit, eget tincidunt nibh pulvinar quam id dui posuere blandit.
Curabitur arcu erat, accumsan id imperdiet et, porttitor at sem. Donec rutrum congue leo eget malesuada. Quisque velit nisi, pretium ut lacinia in, elementum id enim. Donec sollicitudin molestie malesuada.','78','House','360m','2');
insert into properties (property_name, price, currency, property_image,property_image2,property_image3,property_location,beds,baths,description,property_id,property_type,area,garage) values ('Philadelphia, USA', 1800000, '$', '/images/img_3.jpg','/images/img_8.jpg','/images/img_1.jpg','8999 Philadelphia Philo, Ave. 89DC','3 beds','1 baths','Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec velit neque, auctor sit amet aliquam vel, ullamcorper sit amet ligula. Cras ultricies ligula sed magna dictum porta. Curabitur aliquet quam id dui posuere blandit. Mauris blandit aliquet elit, eget tincidunt nibh pulvinar quam id dui posuere blandit.
Curabitur arcu erat, accumsan id imperdiet et, porttitor at sem. Donec rutrum congue leo eget malesuada. Quisque velit nisi, pretium ut lacinia in, elementum id enim. Donec sollicitudin molestie malesuada.','52','Villa','210m','0');
insert into properties (property_name, price, currency, property_image,property_image2,property_image3,property_location,beds,baths,description,property_id,property_type,area,garage) values ('Albuquerque, USA', 650000, '$', '/images/img_4.jpg','/images/img_5.jpg','/images/img_6.jpg','5888 Albuquerque Meta, Ave. 865','2 beds','2 baths','Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec velit neque, auctor sit amet aliquam vel, ullamcorper sit amet ligula. Cras ultricies ligula sed magna dictum porta. Curabitur aliquet quam id dui posuere blandit. Mauris blandit aliquet elit, eget tincidunt nibh pulvinar quam id dui posuere blandit.
Curabitur arcu erat, accumsan id imperdiet et, porttitor at sem. Donec rutrum congue leo eget malesuada. Quisque velit nisi, pretium ut lacinia in, elementum id enim. Donec sollicitudin molestie malesuada.','33','Villa','250m','2');
insert into properties (property_name, price, currency, property_image,property_image2,property_image3,property_location,beds,baths,description,property_id,property_type,area,garage) values ('New York, USA', 155000000, '$', '/images/img_5.jpg','/images/img_2.jpg','/images/img_1.jpg','35200 New York Time Square, Ave. 66DD','2 beds','1 baths','Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec velit neque, auctor sit amet aliquam vel, ullamcorper sit amet ligula. Cras ultricies ligula sed magna dictum porta. Curabitur aliquet quam id dui posuere blandit. Mauris blandit aliquet elit, eget tincidunt nibh pulvinar quam id dui posuere blandit.
Curabitur arcu erat, accumsan id imperdiet et, porttitor at sem. Donec rutrum congue leo eget malesuada. Quisque velit nisi, pretium ut lacinia in, elementum id enim. Donec sollicitudin molestie malesuada.','1','House','150m','1');
insert into properties (property_name, price, currency, property_image,property_image2,property_image3,property_location,beds,baths,description,property_id,property_type,area,garage) values ('Los Angeles, USA', 6500000, '$', '/images/img_6.jpg','/images/img_5.jpg','/images/img_2.jpg','895 Los Angeles Main, Road. Mr.T95','4 beds','1 baths','Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec velit neque, auctor sit amet aliquam vel, ullamcorper sit amet ligula. Cras ultricies ligula sed magna dictum porta. Curabitur aliquet quam id dui posuere blandit. Mauris blandit aliquet elit, eget tincidunt nibh pulvinar quam id dui posuere blandit.
Curabitur arcu erat, accumsan id imperdiet et, porttitor at sem. Donec rutrum congue leo eget malesuada. Quisque velit nisi, pretium ut lacinia in, elementum id enim. Donec sollicitudin molestie malesuada.','96','Villa','200m','2');
insert into properties (property_name, price, currency, property_image,property_image2,property_image3,property_location,beds,baths,description,property_id,property_type,area,garage) values ('Orlando, USA', 740000, '$', '/images/img_7.jpg','/images/img_4.jpg','/images/img_1.jpg','2150 Orlando Gheto, Ave. 66RD','4 beds','2 baths','Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec velit neque, auctor sit amet aliquam vel, ullamcorper sit amet ligula. Cras ultricies ligula sed magna dictum porta. Curabitur aliquet quam id dui posuere blandit. Mauris blandit aliquet elit, eget tincidunt nibh pulvinar quam id dui posuere blandit.
Curabitur arcu erat, accumsan id imperdiet et, porttitor at sem. Donec rutrum congue leo eget malesuada. Quisque velit nisi, pretium ut lacinia in, elementum id enim. Donec sollicitudin molestie malesuada.','25','Villa','350m','2');
insert into properties (property_name, price, currency, property_image,property_image2,property_image3,property_location,beds,baths,description,property_id,property_type,area,garage) values ('Florida, USA', 1291000, '$', '/images/img_8.jpg','/images/img_6.jpg','/images/img_2.jpg','7474 Florida Crock, Ave. 99BH','3 beds','2 baths','Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec velit neque, auctor sit amet aliquam vel, ullamcorper sit amet ligula. Cras ultricies ligula sed magna dictum porta. Curabitur aliquet quam id dui posuere blandit. Mauris blandit aliquet elit, eget tincidunt nibh pulvinar quam id dui posuere blandit.
Curabitur arcu erat, accumsan id imperdiet et, porttitor at sem. Donec rutrum congue leo eget malesuada. Quisque velit nisi, pretium ut lacinia in, elementum id enim. Donec sollicitudin molestie malesuada.','11','House','210m','1');
insert into properties (property_name, price, currency, property_image,property_image2,property_image3,property_location,beds,baths,description,property_id,property_type,area,garage) values ('Florida, USA', 156000, '$', '/images/img_8.jpg','/images/img_6.jpg','/images/img_2.jpg','7654 Florida Crock, Ave. 99BH','3 beds','2 baths','Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec velit neque, auctor sit amet aliquam vel, ullamcorper sit amet ligula. Cras ultricies ligula sed magna dictum porta. Curabitur aliquet quam id dui posuere blandit. Mauris blandit aliquet elit, eget tincidunt nibh pulvinar quam id dui posuere blandit.
Curabitur arcu erat, accumsan id imperdiet et, porttitor at sem. Donec rutrum congue leo eget malesuada. Quisque velit nisi, pretium ut lacinia in, elementum id enim. Donec sollicitudin molestie malesuada.','11','House','210m','1');

